# Generated by Django 4.2.5 on 2023-09-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publications',
            old_name='publication_date',
            new_name='pub_date',
        ),
    ]
