# Generated by Django 4.2.5 on 2023-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_blog', '0003_rename_lastmane_personal_data_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='nickname',
        ),
        migrations.AddField(
            model_name='personal_data_user',
            name='nickname',
            field=models.CharField(default='New_User', max_length=10),
            preserve_default=False,
        ),
    ]
